baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Connected Data Hub'
theme = 'ananke'
[params]
  text_color = 'black'
  background_color_class = "bg-blue"
  body_classes = 'helvetica bg-white'
  post_content_classes = 'helvetica bg-white'
  custom_css = ["custom.css"]
  site_logo = "static/images/cdh_logo.png"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/ConnectedDataHub/ConnectedDataHub.github.io"

[markup.goldmark.renderer]
    unsafe = true
